Repository mana-ethereum/mana, pull requests merged in 2018-05, with the labels that each got.

#13 Fix in_umbrella typo
  apps/evm/mix.exs
Labels: in progress

#8 Adds instructions to setup in README
  README.md
Labels: in progress

#17 Ignore _lexer.erl and _parser.erl files
  .gitignore
Labels: in progress

#18 update nodes because old nodes are not available
  apps/ex_wire/chains/ropsten.json
Labels: in progress

#14 Add CircleCI config
  .circleci/config.yml
Labels: in progress

#19 Remove Exleveldb app and add it as a hex package
  apps/exleveldb/CONTRIBUTING.md
  apps/exleveldb/LICENSE
  apps/exleveldb/README.md
  apps/exleveldb/lib/exleveldb.ex
  apps/exleveldb/lib/protocols/keys.ex
  apps/exleveldb/lib/protocols/values.ex
  apps/exleveldb/mix.exs
  apps/exleveldb/test/exleveldb_test.exs
  apps/exleveldb/test/test_helper.exs
  apps/merkle_patricia_tree/mix.exs
  mix.exs
  mix.lock
Labels: in progress

#24 Gv fix blockchain test
  .circleci/config.yml
  apps/blockchain/lib/blockchain/block.ex
  apps/blockchain/lib/blockchain/transaction.ex
  apps/blockchain/lib/eth_common_test/harness.ex
  apps/blockchain/lib/eth_common_test/helpers.ex
  apps/blockchain/test/blockchain/block_test.exs
  apps/blockchain/test/blockchain/state_test.exs
  apps/blockchain/test/blockchain/transaction_test.exs
  apps/evm/lib/evm/operation/system.ex
Labels: in progress

#28 Add super-important file with github labels
  github-labels.json
Labels: in progress, tag: internal

#37 Add chain_id for blockchain tests that need it
  apps/blockchain/lib/eth_common_test/helpers.ex
  apps/blockchain/test/blockchain/transaction_test.exs
Labels: blockchain, status: in progress

#38 Use define_common_test/3 instead of eth_test/2
  apps/blockchain/lib/eth_common_test/harness.ex
  apps/blockchain/test/blockchain/block_test.exs
Labels: blockchain, status: in progress

#40 Make hex_prefix a part of the merkle_partricia_tree
  apps/abi/mix.lock
  apps/blockchain/mix.lock
  apps/evm/mix.lock
  apps/ex_wire/mix.lock
  apps/exth_crypto/mix.lock
  apps/hex_prefix/.circleci/config.yml
  apps/hex_prefix/.formatter.exs
  apps/hex_prefix/README.md
  apps/hex_prefix/config/config.exs
  apps/hex_prefix/lib/hex_prefix.ex
  apps/hex_prefix/mix.exs
  apps/hex_prefix/mix.lock
  apps/hex_prefix/test/hex_prefix_test.exs
  apps/hex_prefix/test/test_helper.exs
  apps/merkle_patricia_tree/lib/hex_prefix.ex
  apps/merkle_patricia_tree/lib/trie.ex
  apps/merkle_patricia_tree/lib/trie/node.ex
  apps/merkle_patricia_tree/mix.exs
  apps/merkle_patricia_tree/mix.lock
  apps/merkle_patricia_tree/test/hex_prefix_test.exs
  apps/merkle_patricia_tree/test/trie_test.exs
  mix.exs
  mix.lock
Labels: merkle_patricia_tree, status: in progress

#44 Rm apps circleci
  apps/abi/README.md
  apps/blockchain/.circleci/config.yml
  apps/evm/.circleci/config.yml
  apps/evm/README.md
  apps/ex_wire/.circleci/config.yml
  apps/ex_wire/README.md
  apps/exth_crypto/.circleci/config.yml
  apps/merkle_patricia_tree/.circleci/config.yml
  apps/merkle_patricia_tree/README.md
Labels: status: in progress

#45 Merkle-Patricia Tree enhancements
  .circleci/config.yml
  apps/ex_wire/config/dev.exs
  apps/merkle_patricia_tree/lib/db/ets.ex
  apps/merkle_patricia_tree/lib/hex_prefix.ex
  apps/merkle_patricia_tree/lib/list_helper.ex
  apps/merkle_patricia_tree/lib/trie.ex
  apps/merkle_patricia_tree/lib/trie/builder.ex
  apps/merkle_patricia_tree/lib/trie/destroyer.ex
  apps/merkle_patricia_tree/lib/trie/inspector.ex
  apps/merkle_patricia_tree/lib/trie/node.ex
  apps/merkle_patricia_tree/lib/trie/storage.ex
  apps/merkle_patricia_tree/mix.exs
  apps/merkle_patricia_tree/test/hex_prefix_test.exs
  apps/merkle_patricia_tree/test/merkle_patricia_tree_test.exs
  apps/merkle_patricia_tree/test/support/node_helpers.ex
  apps/merkle_patricia_tree/test/test_helper.exs
  apps/merkle_patricia_tree/test/trie/inspector_test.exs
  apps/merkle_patricia_tree/test/trie_test.exs
Labels: status: in progress

#50 Chore/use exth crypto#35
  apps/blockchain/lib/bit_helper.ex
  apps/blockchain/lib/blockchain/account.ex
  apps/blockchain/lib/blockchain/block.ex
  apps/blockchain/lib/blockchain/bloom.ex
  apps/blockchain/lib/blockchain/contract.ex
  apps/blockchain/lib/blockchain/transaction.ex
  apps/blockchain/lib/blockchain/transaction/signature.ex
  apps/blockchain/mix.exs
  apps/blockchain/test/blockchain/account_test.exs
  apps/blockchain/test/blockchain/block_test.exs
  apps/blockchain/test/blockchain/state_test.exs
  apps/blockchain/test/blockchain/transaction_test.exs
  apps/blockchain/test/blockchain_test.exs
  apps/exth_crypto/lib/hash/keccak.ex
Labels: status: in progress

#64 Dialyzer warning fixes PR#1
  apps/blockchain/lib/blockchain/account.ex
  apps/blockchain/lib/blockchain/block.ex
Labels: status: in progress

#22 Kademlia p2p
  apps/ex_wire/lib/ex_wire/kademlia.ex
  apps/ex_wire/lib/ex_wire/kademlia/bucket.ex
  apps/ex_wire/lib/ex_wire/kademlia/config.ex
  apps/ex_wire/lib/ex_wire/kademlia/node.ex
  apps/ex_wire/lib/ex_wire/kademlia/routing_table.ex
  apps/ex_wire/lib/ex_wire/kademlia/server.ex
  apps/ex_wire/lib/ex_wire/kademlia/xor_distance.ex
  apps/ex_wire/lib/ex_wire/util/timestamp.ex
  apps/ex_wire/test/ex_wire/kademlia/bucket_test.exs
  apps/ex_wire/test/ex_wire/kademlia/node_test.exs
  apps/ex_wire/test/ex_wire/kademlia/routing_table_test.exs
  apps/ex_wire/test/ex_wire/kademlia/xor_distance_test.exs
  apps/ex_wire/test/ex_wire/kademlia_test.exs
Labels: in progress, status: in progress

#71 Dialyzer warning fixes #2
  apps/blockchain/lib/blockchain/block.ex
  apps/blockchain/lib/eth_common_test/helpers.ex
  apps/evm/lib/block/header.ex
Labels: status: in progress

#79 Dialyzer warning fixes #3
  apps/blockchain/lib/blockchain/account.ex
  apps/blockchain/lib/blockchain/block.ex
  apps/blockchain/lib/blockchain/blocktree.ex
  apps/blockchain/lib/blockchain/interface/account_interface.ex
  apps/blockchain/lib/blockchain/transaction.ex
Labels: status: in progress

#80 Ignore specific Blockchain app warnings
  .dialyzer.ignore-warnings
  mix.exs
Labels: status: in progress

#51 Add rocksdb (database backend)
  .circleci/config.yml
  apps/blockchain/lib/blockchain/block.ex
  apps/merkle_patricia_tree/README.md
  apps/merkle_patricia_tree/lib/db.ex
  apps/merkle_patricia_tree/lib/db/rocksdb.ex
  apps/merkle_patricia_tree/lib/test.ex
  apps/merkle_patricia_tree/lib/trie.ex
  apps/merkle_patricia_tree/mix.exs
  apps/merkle_patricia_tree/test/db/leveldb_test.exs
  apps/merkle_patricia_tree/test/db/rocksdb_test.exs
  mix.lock
Labels: merkle_patricia_tree, status: blocked, status: in progress

#87 Stop ignoring String10MbData test
  .circleci/config.yml
  apps/blockchain/test/blockchain/transaction_test.exs
Labels: status: in progress

#73 Node discovery with network
  apps/ex_wire/config/dev.exs
  apps/ex_wire/config/test.exs
  apps/ex_wire/lib/ex_wire.ex
  apps/ex_wire/lib/ex_wire/adapter/udp.ex
  apps/ex_wire/lib/ex_wire/config.ex
  apps/ex_wire/lib/ex_wire/handler/ping.ex
  apps/ex_wire/lib/ex_wire/handler/pong.ex
  apps/ex_wire/lib/ex_wire/kademlia.ex
  apps/ex_wire/lib/ex_wire/kademlia/bucket.ex
  apps/ex_wire/lib/ex_wire/kademlia/node.ex
  apps/ex_wire/lib/ex_wire/kademlia/routing_table.ex
  apps/ex_wire/lib/ex_wire/kademlia/server.ex
  apps/ex_wire/lib/ex_wire/message/ping.ex
  apps/ex_wire/lib/ex_wire/network.ex
  apps/ex_wire/lib/ex_wire/node_discovery_supervisor.ex
  apps/ex_wire/lib/ex_wire/protocol.ex
  apps/ex_wire/test/ex_wire/kademlia/bucket_test.exs
  apps/ex_wire/test/ex_wire/kademlia/routing_table_test.exs
  apps/ex_wire/test/ex_wire/kademlia_test.exs
  apps/ex_wire/test/ex_wire/message/ping_test.exs
  apps/ex_wire/test/ex_wire_test.exs
  apps/ex_wire/test/integration/remote_connection_test.exs
  apps/ex_wire/test/integration/wire_to_wire_test.exs
  apps/ex_wire/test/support/ex_wire/adapter/test.ex
  apps/ex_wire/test/support/ex_wire/test_helper.ex
Labels: ex_wire, priority: high, status: in progress

#86 Bug fixes, initial refactoring
  .dialyzer.ignore-warnings
  apps/blockchain/README.md
  apps/blockchain/lib/blockchain/account.ex
  apps/blockchain/lib/blockchain/account/storage.ex
  apps/blockchain/lib/blockchain/block.ex
  apps/blockchain/lib/blockchain/block/holistic_validity.ex
  apps/blockchain/lib/blockchain/blocktree.ex
  apps/blockchain/lib/blockchain/bloom.ex
  apps/blockchain/lib/blockchain/chain.ex
  apps/blockchain/lib/blockchain/contract.ex
  apps/blockchain/lib/blockchain/genesis.ex
  apps/blockchain/lib/blockchain/interface/account_interface.ex
  apps/blockchain/lib/blockchain/transaction.ex
  apps/blockchain/lib/blockchain/transaction/receipt.ex
  apps/blockchain/lib/blockchain/transaction/signature.ex
  apps/blockchain/lib/math_helper.ex
  apps/blockchain/test/blockchain/account_test.exs
  apps/blockchain/test/blockchain/block_test.exs
  apps/blockchain/test/blockchain/state_test.exs
  apps/blockchain/test/blockchain/transaction_test.exs
  apps/blockchain/test/test_helper.exs
  apps/evm/lib/block/header.ex
  apps/evm/lib/evm.ex
  apps/evm/lib/evm/address.ex
  apps/evm/lib/evm/exec_env.ex
  apps/evm/lib/evm/gas.ex
  apps/evm/lib/evm/log_entry.ex
  apps/evm/lib/evm/machine_code.ex
  apps/evm/lib/evm/operation/stack_memory_storage_and_flow.ex
  apps/evm/lib/evm/operation/system.ex
  apps/evm/lib/evm/vm.ex
  apps/evm/test/evm_test.exs
  apps/ex_wire/lib/ex_wire/config.ex
  apps/ex_wire/lib/ex_wire/struct/block_queue.ex
  apps/ex_wire/lib/ex_wire/sync.ex
  apps/ex_wire/test/ex_wire/kademlia/routing_table_test.exs
  apps/ex_wire/test/support/ex_wire/test_helper.ex
  apps/merkle_patricia_tree/README.md
  apps/merkle_patricia_tree/lib/db.ex
  apps/merkle_patricia_tree/lib/db/ets.ex
  apps/merkle_patricia_tree/lib/db/rocksdb.ex
  apps/merkle_patricia_tree/lib/hex_prefix.ex
  apps/merkle_patricia_tree/lib/list_helper.ex
  apps/merkle_patricia_tree/lib/trie.ex
  apps/merkle_patricia_tree/lib/trie/destroyer.ex
  apps/merkle_patricia_tree/lib/trie/helper.ex
  apps/merkle_patricia_tree/lib/trie/inspector.ex
  apps/merkle_patricia_tree/lib/trie/node.ex
  apps/merkle_patricia_tree/lib/trie/storage.ex
  apps/merkle_patricia_tree/lib/trie/verifier.ex
  apps/merkle_patricia_tree/test/trie_test.exs
Labels: status: in progress

#92 add cargo directories for dialyzer ci cache
  .circleci/config.yml
Labels: status: in progress

#91 exth crypto improvements
  apps/exth_crypto/lib/aes.ex
  apps/exth_crypto/lib/ecies.ex
  apps/exth_crypto/lib/hash.ex
  apps/exth_crypto/lib/key.ex
  apps/exth_crypto/lib/mac.ex
  apps/exth_crypto/lib/math.ex
  apps/exth_crypto/lib/signature.ex
  apps/exth_crypto/mix.exs
  apps/exth_crypto/test/aes_test.exs
  apps/exth_crypto/test/ecies_test.exs
  apps/exth_crypto/test/key_test.exs
  apps/exth_crypto/test/mac_test.exs
  apps/exth_crypto/test/math_test.exs
  apps/exth_crypto/test/signature/signature_test.exs
  apps/exth_crypto/test/signature_test.exs
Labels: status: in progress

#94 Use rocksdb by default
  .gitignore
  apps/ex_wire/lib/ex_wire.ex
  apps/ex_wire/test/ex_wire/kademlia_test.exs
  apps/ex_wire/test/support/ex_wire/test_helper.ex
Labels: status: in progress

#96 Add Rust requirement to README
  README.md
Labels: status: in progress, tag: documentation

#90 Neighbours command
  apps/ex_wire/config/config.exs
  apps/ex_wire/config/test.exs
  apps/ex_wire/lib/ex_wire/adapter/udp.ex
  apps/ex_wire/lib/ex_wire/config.ex
  apps/ex_wire/lib/ex_wire/crypto.ex
  apps/ex_wire/lib/ex_wire/handler.ex
  apps/ex_wire/lib/ex_wire/handler/find_neighbours.ex
  apps/ex_wire/lib/ex_wire/handler/neighbours.ex
  apps/ex_wire/lib/ex_wire/handler/ping.ex
  apps/ex_wire/lib/ex_wire/handler/pong.ex
  apps/ex_wire/lib/ex_wire/kademlia.ex
  apps/ex_wire/lib/ex_wire/kademlia/node.ex
  apps/ex_wire/lib/ex_wire/kademlia/routing_table.ex
  apps/ex_wire/lib/ex_wire/kademlia/server.ex
  apps/ex_wire/lib/ex_wire/message.ex
  apps/ex_wire/lib/ex_wire/network.ex
  apps/ex_wire/lib/ex_wire/node_discovery_supervisor.ex
  apps/ex_wire/test/ex_wire/handler/pong_test.exs
  apps/ex_wire/test/ex_wire/kademlia/node_test.exs
  apps/ex_wire/test/ex_wire/kademlia/routing_table_test.exs
  apps/ex_wire/test/ex_wire/kademlia_test.exs
  apps/ex_wire/test/ex_wire/network_test.exs
  apps/ex_wire/test/ex_wire_test.exs
  apps/ex_wire/test/integration/node_discovery_test.exs
  apps/ex_wire/test/integration/remote_connection_test.exs
  apps/ex_wire/test/integration/wire_to_wire_test.exs
Labels: status: in progress

#111 Feature/update chains
  apps/blockchain/README.md
  apps/blockchain/chains/ropsten.json
  apps/blockchain/lib/blockchain/block.ex
  apps/blockchain/lib/blockchain/block/holistic_validity.ex
  apps/blockchain/lib/blockchain/blocktree.ex
  apps/blockchain/lib/blockchain/chain.ex
  apps/blockchain/lib/blockchain/genesis.ex
  apps/blockchain/lib/test.ex
  apps/blockchain/test/blockchain/block_test.exs
  apps/blockchain/test/blockchain/chain_test.exs
  apps/blockchain/test/ropsten_test.exs
  apps/blockchain/test/support/ropsten.dat
  apps/ex_wire/chains/ropsten.json
  chains/byzantium_test.json
  chains/constantinople_test.json
  chains/homestead_test.json
  chains/ropsten.json
Labels: status: in progress

#98 Precompiled Contract: SHA2-256
  apps/evm/lib/evm/builtin.ex
  apps/evm/test/evm/builtin_test.exs
Labels: evm

#118 Do not pass unneeded peer's uri host as argument
  apps/ex_wire/lib/ex_wire/adapter/tcp/server.ex
  apps/ex_wire/lib/ex_wire/handshake/eip_8.ex
  apps/ex_wire/lib/ex_wire/handshake/handshake.ex
  apps/ex_wire/test/ex_wire/handshake/handshake_test.exs
Labels: status: in progress

#100 Precompiled Contract: Identity
  apps/evm/lib/evm/builtin.ex
Labels: evm, status: in progress

#102 Precompiled Contract: ripmed160
  apps/evm/lib/evm/builtin.ex
Labels: status: in progress

#101 Precompiled Contract: ecrec
  apps/evm/lib/evm/builtin.ex
Labels: evm, status: in progress

#122 Fix Secrets.derive_secrets/7 function
  apps/ex_wire/lib/ex_wire/framing/secrets.ex
  apps/ex_wire/lib/ex_wire/handshake/handshake.ex
  apps/ex_wire/test/ex_wire/framing/secrets_test.exs
Labels: ex_wire, priority: medium, status: in progress, tag: bug fix
