Repository mana-ethereum/mana, pull requests merged in 2018-12, with the labels that each got.

#689 Wire Sub-Protocol Capability Configuration
  apps/ex_wire/lib/ex_wire/dev_p2p.ex
  apps/ex_wire/lib/ex_wire/packet/capability/eth.ex
  apps/ex_wire/lib/ex_wire/packet/capability/mana.ex
  apps/ex_wire/lib/ex_wire/packet/protocol/hello.ex
Labels: status: review needed

#693 fix first bit calculation for small numbers
  apps/evm/lib/evm/builtin/mod_exp.ex
  apps/evm/test/evm/builtin/mod_exp_test.exs
Labels: status: in progress, status: review needed

#691 Add Block `with_hash` and `fetch_block_hash` helpers
  apps/blockchain/lib/blockchain/block.ex
Labels: status: in progress

#688 Peer mngmt #639
  apps/ex_wire/config/dev.exs
  apps/ex_wire/config/test.exs
  apps/ex_wire/lib/ex_wire.ex
  apps/ex_wire/lib/ex_wire/connection_observer.ex
  apps/ex_wire/lib/ex_wire/kademlia.ex
  apps/ex_wire/lib/ex_wire/kademlia/discovery.ex
  apps/ex_wire/lib/ex_wire/kademlia/server.ex
  apps/ex_wire/lib/ex_wire/node_discovery_supervisor.ex
  apps/ex_wire/lib/ex_wire/p2p/connection.ex
  apps/ex_wire/lib/ex_wire/p2p/server.ex
  apps/ex_wire/lib/ex_wire/peer_supervisor.ex
  apps/ex_wire/lib/ex_wire/tcp/inbound_connections_supervisor.ex
  apps/ex_wire/lib/ex_wire/tcp/listener.ex
  apps/ex_wire/lib/ex_wire/tcp_listening_supervisor.ex
  apps/ex_wire/test/ex_wire/connection_observer_test.exs
  apps/ex_wire/test/ex_wire/sync_test.exs
  apps/ex_wire/test/ex_wire/tcp_listening_supervisor_test.exs
  apps/ex_wire/test/support/ex_wire/fake_kademlia.ex
Labels: devp2p, priority: medium, status: review needed

#698 count bits only for 256 bit numbers
  apps/evm/lib/evm/builtin/mod_exp.ex
  apps/evm/test/evm/builtin/mod_exp_test.exs
Labels: status: in progress, status: review needed

#700 fix block hash key
  apps/blockchain/lib/blockchain/block.ex
Labels: status: in progress

#703 Fix difficulty calculation for Constantinople hardfork
  apps/blockchain/lib/blockchain/block.ex
  apps/blockchain/lib/blockchain/chain.ex
  apps/evm/test/block/header_test.exs
  chains/ropsten.json
Labels: status: in progress

#701 getting p2p version and caps into the peer
  apps/ex_wire/lib/ex_wire/connection_observer.ex
  apps/ex_wire/lib/ex_wire/dev_p2p.ex
  apps/ex_wire/lib/ex_wire/p2p/manager.ex
  apps/ex_wire/lib/ex_wire/packet.ex
  apps/ex_wire/lib/ex_wire/packet/protocol/hello.ex
  apps/ex_wire/lib/ex_wire/struct/peer.ex
  apps/ex_wire/test/ex_wire/dev_p2p_test.exs
  apps/jsonrpc2/test/jsonrpc2/mana_handler_test.exs
Labels: status: in progress

#705 Update README sync status
  README.md
Labels: status: in progress

#695 log to disk
  .formatter.exs
  .gitignore
  apps/blockchain/mix.exs
  apps/cli/mix.exs
  apps/evm/mix.exs
  apps/ex_wire/mix.exs
  apps/exth/mix.exs
  apps/exth_crypto/mix.exs
  apps/jsonrpc2/mix.exs
  apps/merkle_patricia_tree/mix.exs
  config/config.exs
  mix.exs
  mix.lock
Labels: status: review needed

#709 add json rpc fields
  apps/blockchain/lib/blockchain/block.ex
  apps/blockchain/test/blockchain/block_test.exs
  apps/evm/lib/block/header.ex
  apps/jsonrpc2/lib/bridge/sync.ex
  apps/jsonrpc2/lib/jsonrpc2/response/block.ex
  apps/jsonrpc2/test/jsonrpc2/mana_handler_test.exs
  apps/jsonrpc2/test/jsonrpc2/response/block_test.exs
  apps/jsonrpc2/test/support/bridge_sync_mock.ex
Labels: status: in progress, status: review needed

#714 JSON RPC transaction
  apps/jsonrpc2/lib/jsonrpc2/response/transaction.ex
  apps/jsonrpc2/test/jsonrpc2/response/transaction_test.exs
  apps/jsonrpc2/test/support/test_factory.ex
Labels: status: in progress, status: review needed

#712 simple escript that starts a release and performs tests
  .circleci/config.yml
  .formatter.exs
  .gitignore
  priv/itest/README
  priv/itest/mix.exs
  priv/itest/mix.lock
  priv/itest/release.ex
  priv/itest/starter.ex
  priv/itest/websocket_test.ex
Labels: status: review needed

#716 add transaction getter methods for JSON RPC API
  apps/jsonrpc2/lib/bridge/sync.ex
  apps/jsonrpc2/lib/jsonrpc2/spec_handler.ex
  apps/jsonrpc2/test/jsonrpc2/mana_handler_test.exs
  apps/jsonrpc2/test/support/bridge_sync_mock.ex
Labels: status: in progress

#717 return transactions with block for JSON RPC API
  apps/jsonrpc2/lib/bridge/sync.ex
  apps/jsonrpc2/lib/jsonrpc2/response/block.ex
  apps/jsonrpc2/lib/jsonrpc2/spec_handler.ex
  apps/jsonrpc2/test/jsonrpc2/mana_handler_test.exs
  apps/jsonrpc2/test/jsonrpc2/response/block_test.exs
  apps/jsonrpc2/test/support/bridge_sync_mock.ex
Labels: status: in progress, status: review needed

#720 Support Capabilities with Overlapping Packets 706
  apps/ex_wire/config/test.exs
  apps/ex_wire/lib/ex_wire/dev_p2p/session.ex
  apps/ex_wire/lib/ex_wire/packet/capability.ex
  apps/ex_wire/lib/ex_wire/packet/capability/eth.ex
  apps/ex_wire/lib/ex_wire/packet/capability/eth/get_node_data.ex
  apps/ex_wire/lib/ex_wire/packet/capability/eth/get_receipts.ex
  apps/ex_wire/lib/ex_wire/packet/capability/eth/node_data.ex
  apps/ex_wire/lib/ex_wire/packet/capability/eth/receipts.ex
  apps/ex_wire/lib/ex_wire/packet/capability/mana.ex
  apps/ex_wire/lib/ex_wire/packet/capability/par.ex
  apps/ex_wire/lib/ex_wire/packet/capability/par/block_bodies.ex
  apps/ex_wire/lib/ex_wire/packet/capability/par/block_headers.ex
  apps/ex_wire/lib/ex_wire/packet/capability/par/get_block_bodies.ex
  apps/ex_wire/lib/ex_wire/packet/capability/par/get_block_headers.ex
  apps/ex_wire/lib/ex_wire/packet/capability/par/get_node_data.ex
  apps/ex_wire/lib/ex_wire/packet/capability/par/get_receipts.ex
  apps/ex_wire/lib/ex_wire/packet/capability/par/new_block.ex
  apps/ex_wire/lib/ex_wire/packet/capability/par/new_block_hashes.ex
  apps/ex_wire/lib/ex_wire/packet/capability/par/node_data.ex
  apps/ex_wire/lib/ex_wire/packet/capability/par/receipts.ex
  apps/ex_wire/lib/ex_wire/packet/capability/par/transactions.ex
  apps/ex_wire/lib/ex_wire/packet/packet_id_map.ex
  apps/ex_wire/test/ex_wire/packet/capability/eth/get_node_data_test.exs
  apps/ex_wire/test/ex_wire/packet/capability/eth/get_receipts_test.exs
  apps/ex_wire/test/ex_wire/packet/capability/eth/node_data_test.exs
  apps/ex_wire/test/ex_wire/packet/capability/eth/receipts_test.exs
  apps/ex_wire/test/ex_wire/packet/capability/par/get_node_data_test.exs
  apps/ex_wire/test/ex_wire/packet/capability/par/get_receipts_test.exs
  apps/ex_wire/test/ex_wire/packet/capability/par/node_data_test.exs
  apps/ex_wire/test/ex_wire/packet/capability/par/receipts_test.exs
  apps/ex_wire/test/ex_wire/packet/capability_test.exs
  apps/ex_wire/test/ex_wire/packet/packet_id_map_test.exs
Labels: status: in progress

#722 fix dynamicAccountOverwriteempty test
  README.md
  apps/blockchain/lib/blockchain/account/repo.ex
  apps/blockchain/test/blockchain/blockchain_state_test.exs
  apps/blockchain/test/blockchain_test.exs
Labels: status: in progress, status: review needed

#724 decode block number in json rpc
  apps/exth/lib/exth.ex
  apps/jsonrpc2/lib/bridge/sync.ex
  apps/jsonrpc2/lib/jsonrpc2/spec_handler.ex
  apps/jsonrpc2/test/jsonrpc2/mana_handler_test.exs
  apps/jsonrpc2/test/support/bridge_sync_mock.ex
Labels: status: in progress, status: review needed

#727 parallelize evm tests
  apps/evm/test/evm_test.exs
Labels: status: in progress, status: review needed

#729 add `getCode` json rpc method
  apps/jsonrpc2/lib/bridge/sync.ex
  apps/jsonrpc2/lib/jsonrpc2/spec_handler.ex
  apps/jsonrpc2/test/jsonrpc2/mana_handler_test.exs
  apps/jsonrpc2/test/support/bridge_sync_mock.ex
Labels: status: in progress, status: review needed

#732 return transaction by hash
  apps/blockchain/lib/blockchain/block.ex
  apps/blockchain/lib/blockchain/transaction.ex
  apps/blockchain/test/blockchain/block_test.exs
  apps/jsonrpc2/lib/bridge/sync.ex
  apps/jsonrpc2/lib/jsonrpc2/response/block.ex
  apps/jsonrpc2/lib/jsonrpc2/spec_handler.ex
  apps/jsonrpc2/test/jsonrpc2/mana_handler_test.exs
  apps/jsonrpc2/test/support/bridge_sync_mock.ex
Labels: status: in progress, status: review needed

#733 fetch receipt from database for JSON RPC
  apps/blockchain/lib/blockchain/block.ex
  apps/blockchain/test/blockchain/block_test.exs
  apps/jsonrpc2/lib/bridge/sync.ex
  apps/jsonrpc2/lib/jsonrpc2/response/receipt.ex
  apps/jsonrpc2/lib/jsonrpc2/response/transaction.ex
  apps/jsonrpc2/lib/jsonrpc2/spec_handler.ex
  apps/jsonrpc2/test/jsonrpc2/mana_handler_test.exs
  apps/jsonrpc2/test/jsonrpc2/response/receipt_test.exs
  apps/jsonrpc2/test/support/bridge_sync_mock.ex
  apps/jsonrpc2/test/support/test_factory.ex
Labels: status: in progress

#735 finish receipt serialization
  apps/blockchain/lib/blockchain/block.ex
  apps/blockchain/lib/blockchain/transaction.ex
  apps/blockchain/test/blockchain/block_test.exs
  apps/jsonrpc2/lib/jsonrpc2/response/block.ex
  apps/jsonrpc2/lib/jsonrpc2/response/receipt.ex
  apps/jsonrpc2/lib/jsonrpc2/response/transaction.ex
  apps/jsonrpc2/test/jsonrpc2/mana_handler_test.exs
  apps/jsonrpc2/test/jsonrpc2/response/block_test.exs
  apps/jsonrpc2/test/jsonrpc2/response/receipt_test.exs
  apps/jsonrpc2/test/jsonrpc2/response/transaction_test.exs
  apps/jsonrpc2/test/support/test_factory.ex
Labels: status: in progress

#737 Uncle getter methods for JSON RPC API
  apps/blockchain/lib/blockchain/block.ex
  apps/jsonrpc2/lib/bridge/sync.ex
  apps/jsonrpc2/lib/jsonrpc2/spec_handler.ex
  apps/jsonrpc2/test/jsonrpc2/mana_handler_test.exs
  apps/jsonrpc2/test/support/bridge_sync_mock.ex
Labels: status: in progress, status: review needed

#736 encode hex values according to Ethereum JSON RPC spec
  apps/jsonrpc2/lib/jsonrpc2/response/block.ex
  apps/jsonrpc2/lib/jsonrpc2/response/helpers.ex
  apps/jsonrpc2/lib/jsonrpc2/response/receipt.ex
  apps/jsonrpc2/lib/jsonrpc2/response/transaction.ex
  apps/jsonrpc2/test/jsonrpc2/mana_handler_test.exs
  apps/jsonrpc2/test/jsonrpc2/response/block_test.exs
  apps/jsonrpc2/test/jsonrpc2/response/receipt_test.exs
  apps/jsonrpc2/test/jsonrpc2/response/transaction_test.exs
Labels: status: in progress, status: review needed

#738 fix encoding for uncle serialization
  apps/jsonrpc2/test/jsonrpc2/mana_handler_test.exs
Labels: status: in progress, status: review needed

#734 Fixing warp processor caching trie thread safety issues
  apps/ex_wire/lib/ex_wire/p2p/server.ex
  apps/ex_wire/lib/ex_wire/sync.ex
  apps/ex_wire/lib/ex_wire/sync/warp_processor.ex
  apps/merkle_patricia_tree/lib/merkle_patricia_tree/caching_trie.ex
  apps/merkle_patricia_tree/lib/merkle_patricia_tree/trie.ex
  apps/merkle_patricia_tree/lib/merkle_patricia_tree/trie_storage.ex
Labels: status: review needed

#740 validate input params for JSON RPC API
  apps/jsonrpc2/lib/jsonrpc2/response/helpers.ex
  apps/jsonrpc2/lib/jsonrpc2/spec_handler.ex
  apps/jsonrpc2/test/jsonrpc2/mana_handler_test.exs
Labels: status: in progress, status: review needed

#743 Improve Empty BlockHeaders Response Handling
  apps/ex_wire/lib/ex_wire/sync.ex
Labels: status: review needed

#742 Adding Header.to_string() that is helpful for debugging
  apps/evm/lib/block/header.ex
Labels: status: review needed

#741 Improving packet_id_map default map function and check
  apps/ex_wire/lib/ex_wire/dev_p2p/session.ex
  apps/ex_wire/lib/ex_wire/packet/packet_id_map.ex
  apps/ex_wire/test/ex_wire/packet/packet_id_map_test.exs
Labels: status: review needed

#744 implement `eth_getStorageAt` JSON RPC method
  apps/jsonrpc2/lib/bridge/sync.ex
  apps/jsonrpc2/lib/jsonrpc2/spec_handler.ex
  apps/jsonrpc2/test/jsonrpc2/mana_handler_test.exs
  apps/jsonrpc2/test/support/bridge_sync_mock.ex
Labels: status: in progress, status: review needed

#745 improve json rpc tests
  apps/jsonrpc2/test/jsonrpc2/mana_handler_test.exs
Labels: status: in progress, status: review needed

#746 handle not found blocks in RPC client
  apps/cli/lib/block_provider/rpc.ex
Labels: status: in progress, status: review needed

#748 fix `eth_blockNumber` JSON RPC method
  apps/jsonrpc2/lib/jsonrpc2/spec_handler.ex
  apps/jsonrpc2/test/jsonrpc2/mana_handler_test.exs
Labels: status: in progress, status: review needed

#747 implement `eth_getTransactionCount` JSON RPC method
  apps/jsonrpc2/lib/bridge/sync.ex
  apps/jsonrpc2/lib/jsonrpc2/spec_handler.ex
  apps/jsonrpc2/test/jsonrpc2/mana_handler_test.exs
  apps/jsonrpc2/test/support/bridge_sync_mock.ex
Labels: status: in progress, status: review needed
