Repository mana-ethereum/mana, pull requests merged in 2018-09, with the labels that each got.

#397 add elliptic curve addition and multiplication builtin contracts
  .dialyzer.ignore-warnings
  README.md
  apps/blockchain/test/blockchain/state_test.exs
  apps/blockchain/test/support/byzantium_failing_tests.txt
  apps/evm/lib/evm/builtin.ex
  apps/evm/lib/evm/configuration.ex
  apps/evm/lib/evm/configuration/byzantium.ex
  apps/evm/lib/evm/configuration/eip150.ex
  apps/evm/lib/evm/configuration/eip158.ex
  apps/evm/lib/evm/configuration/frontier.ex
  apps/evm/lib/evm/configuration/homestead.ex
  apps/evm/lib/evm/message_call.ex
  apps/evm/lib/evm/operation/environmental_information.ex
  apps/evm/mix.exs
  apps/evm/test/evm/builtin_test.exs
  apps/evm/test/evm/operation/environmental_information_test.exs
Labels: evm, status: in progress

#388 Delete unnecessary license files, clean up README docs
  apps/blockchain/README.md
  apps/blockchain/mix.exs
  apps/evm/LICENSE.md
  apps/evm/README.md
  apps/evm/mix.exs
  apps/exth_crypto/README.md
  apps/merkle_patricia_tree/LICENSE.md
  apps/merkle_patricia_tree/README.md
Labels: status: in progress

#410 Handle Disconnect, Ping, and Status packets
  apps/ex_wire/.iex.exs
  apps/ex_wire/config/dev.exs
  apps/ex_wire/lib/ex_wire.ex
  apps/ex_wire/lib/ex_wire/p2p.ex
  apps/ex_wire/lib/ex_wire/p2p/server.ex
  apps/ex_wire/lib/ex_wire/packet/status.ex
  apps/ex_wire/lib/ex_wire/peer_supervisor.ex
  apps/ex_wire/lib/ex_wire/sync.ex
Labels: ex_wire, status: in progress

#411 add gitter badge
  README.md
Labels: status: in progress

#412 Validate before executing transactions
  apps/blockchain/lib/blockchain/block.ex
  apps/blockchain/lib/blockchain/transaction.ex
  apps/blockchain/lib/blockchain/transaction/validity.ex
  apps/blockchain/test/blockchain/block_test.exs
  apps/blockchain/test/blockchain/transaction/validity_test.exs
Labels: status: in progress

#413 fix libsecp256k1 compiletion on linux
  .credo.exs
  apps/blockchain/lib/blockchain/account/storage.ex
  apps/blockchain/lib/blockchain/chain.ex
  apps/blockchain/lib/blockchain/transaction/signature.ex
  apps/blockchain/mix.exs
  apps/blockchain/scripts/generate_state_tests.ex
  apps/blockchain/test/blockchain/transaction_test.exs
  apps/evm/lib/evm/refunds.ex
  apps/evm/lib/helpers.ex
  apps/evm/mix.exs
  apps/evm/test/evm/operation/block_information_test.exs
  apps/ex_wire/mix.exs
  apps/ex_wire/test/ex_wire/framing/secrets_test.exs
  apps/exth_crypto/mix.exs
  apps/merkle_patricia_tree/lib/merkle_patricia_tree/trie/verifier.ex
  apps/merkle_patricia_tree/mix.exs
  bin/setup
  mix.exs
  mix.lock
Labels: status: in progress, tag: internal

#406 EIP197 elliptic curve pairing
  README.md
  apps/blockchain/test/blockchain/state_test.exs
  apps/blockchain/test/support/byzantium_failing_tests.txt
  apps/evm/lib/evm/builtin.ex
  apps/evm/lib/evm/configuration.ex
  apps/evm/lib/evm/configuration/byzantium.ex
  apps/evm/lib/evm/configuration/eip150.ex
  apps/evm/lib/evm/configuration/eip158.ex
  apps/evm/lib/evm/configuration/frontier.ex
  apps/evm/lib/evm/configuration/homestead.ex
  apps/evm/lib/evm/message_call.ex
  apps/evm/mix.exs
  mix.lock
Labels: status: in progress

#422 use correct client name
  apps/blockchain/README.md
  apps/blockchain/test/ropsten_test.exs
  apps/ex_wire/lib/ex_wire/packet/hello.ex
  apps/ex_wire/mix.exs
  apps/exth_crypto/lib/exth_crypto/ecies/ecdh.ex
  apps/exth_crypto/lib/exth_crypto/mac.ex
  apps/merkle_patricia_tree/mix.exs
  mix.exs
Labels: status: in progress

#420 implement extcodehash
  .dialyzer.ignore-warnings
  apps/blockchain/lib/blockchain/interface/account_interface.ex
  apps/evm/lib/evm/configuration.ex
  apps/evm/lib/evm/configuration/byzantium.ex
  apps/evm/lib/evm/configuration/constantinople.ex
  apps/evm/lib/evm/configuration/eip150.ex
  apps/evm/lib/evm/configuration/eip158.ex
  apps/evm/lib/evm/configuration/frontier.ex
  apps/evm/lib/evm/configuration/homestead.ex
  apps/evm/lib/evm/functions.ex
  apps/evm/lib/evm/gas.ex
  apps/evm/lib/evm/interface/account_interface.ex
  apps/evm/lib/evm/interface/mock/mock_account_interface.ex
  apps/evm/lib/evm/operation/environmental_information.ex
  apps/evm/lib/evm/operation/metadata/environmental_information.ex
Labels: evm, status: in progress

#423 Turns EVM.address => Account.Address in interface
  .circleci/config.yml
  README.md
  apps/blockchain/lib/blockchain/account.ex
  apps/blockchain/lib/blockchain/account/address.ex
  apps/blockchain/lib/blockchain/contract/create_contract.ex
  apps/blockchain/lib/blockchain/interface/account_interface.ex
  apps/blockchain/test/blockchain/account/address_test.exs
  apps/blockchain/test/blockchain/block_test.exs
  apps/blockchain/test/blockchain/contract/create_contract_test.exs
  apps/blockchain/test/blockchain/transaction_test.exs
  apps/evm/lib/evm/address.ex
  apps/evm/lib/evm/operation/system.ex
  apps/ex_wire/config/dev.exs
Labels: blockchain, evm, status: in progress

#405 Implement EIP-658
  .dialyzer.ignore-warnings
  apps/blockchain/lib/blockchain/block.ex
  apps/blockchain/lib/blockchain/block/holistic_validity.ex
  apps/blockchain/lib/blockchain/contract.ex
  apps/blockchain/lib/blockchain/contract/create_contract.ex
  apps/blockchain/lib/blockchain/contract/message_call.ex
  apps/blockchain/lib/blockchain/interface/account_interface.ex
  apps/blockchain/lib/blockchain/transaction.ex
  apps/blockchain/scripts/generate_state_tests.ex
  apps/blockchain/test/blockchain/block_test.exs
  apps/blockchain/test/blockchain/contract/message_call_test.exs
  apps/blockchain/test/blockchain/state_test.exs
  apps/blockchain/test/blockchain/transaction_test.exs
Labels: blockchain, status: in progress

#425 update links, add testing note
  README.md
  apps/blockchain/README.md
  apps/evm/README.md
  apps/exth_crypto/LICENSE.md
  apps/merkle_patricia_tree/README.md
Labels: status: in progress

#427 Add debugging tools documentation
  README.md
  apps/evm/README.md
  apps/evm/lib/evm/logger.ex
Labels: evm, status: in progress, tag: documentation

#430 fix output in message call
  apps/blockchain/test/blockchain/state_test.exs
  apps/blockchain/test/blockchain_test.exs
  apps/evm/lib/evm/message_call.ex
  apps/evm/lib/evm/operation/system.ex
Labels: status: in progress

#426 Create2 [EIP-1014]
  .dialyzer.ignore-warnings
  apps/blockchain/lib/blockchain/contract/create_contract.ex
  apps/blockchain/lib/blockchain/interface/account_interface.ex
  apps/blockchain/test/blockchain/state_test.exs
  apps/blockchain/test/blockchain_test.exs
  apps/evm/lib/evm/address.ex
  apps/evm/lib/evm/configuration.ex
  apps/evm/lib/evm/configuration/byzantium.ex
  apps/evm/lib/evm/configuration/constantinople.ex
  apps/evm/lib/evm/configuration/eip150.ex
  apps/evm/lib/evm/configuration/eip158.ex
  apps/evm/lib/evm/configuration/frontier.ex
  apps/evm/lib/evm/configuration/homestead.ex
  apps/evm/lib/evm/functions.ex
  apps/evm/lib/evm/gas.ex
  apps/evm/lib/evm/interface/account_interface.ex
  apps/evm/lib/evm/interface/mock/mock_account_interface.ex
  apps/evm/lib/evm/operation.ex
  apps/evm/lib/evm/operation/metadata/system.ex
  apps/evm/lib/evm/operation/system.ex
Labels: status: in progress

#432 Update dialyxir
  mix.exs
  mix.lock
Labels: status: in progress

#433 EIP-1283
  .dialyzer.ignore-warnings
  apps/blockchain/lib/blockchain/contract/create_contract.ex
  apps/blockchain/lib/blockchain/contract/message_call.ex
  apps/blockchain/lib/blockchain/interface/account_interface.ex
  apps/blockchain/lib/blockchain/interface/account_interface/cache.ex
  apps/blockchain/lib/blockchain/transaction.ex
  apps/blockchain/test/blockchain/contract/create_contract_test.exs
  apps/blockchain/test/blockchain/contract/message_call_test.exs
  apps/blockchain/test/blockchain/interface/account_interface/cache_test.exs
  apps/evm/lib/evm/configuration.ex
  apps/evm/lib/evm/configuration/byzantium.ex
  apps/evm/lib/evm/configuration/constantinople.ex
  apps/evm/lib/evm/configuration/eip150.ex
  apps/evm/lib/evm/configuration/eip158.ex
  apps/evm/lib/evm/configuration/frontier.ex
  apps/evm/lib/evm/configuration/homestead.ex
  apps/evm/lib/evm/exec_env.ex
  apps/evm/lib/evm/gas.ex
  apps/evm/lib/evm/interface/account_interface.ex
  apps/evm/lib/evm/interface/mock/mock_account_interface.ex
  apps/evm/lib/evm/refunds.ex
  apps/evm/lib/evm/refunds/sstore.ex
Labels: status: in progress

#438 EIP-1283 improvements
  .dialyzer.ignore-warnings
  apps/blockchain/lib/blockchain/interface/account_interface.ex
  apps/blockchain/lib/blockchain/interface/account_interface/cache.ex
  apps/blockchain/test/blockchain/contract/message_call_test.exs
  apps/blockchain/test/blockchain/interface/account_interface/cache_test.exs
  apps/evm/lib/evm/gas.ex
  apps/evm/lib/evm/refunds/sstore.ex
Labels: status: in progress

#440 return account_interface instead of state
  apps/blockchain/lib/blockchain/contract/create_contract.ex
  apps/blockchain/lib/blockchain/contract/message_call.ex
  apps/blockchain/lib/blockchain/interface/account_interface.ex
  apps/blockchain/lib/blockchain/transaction.ex
  apps/blockchain/test/blockchain/contract/create_contract_test.exs
  apps/blockchain/test/blockchain/contract/message_call_test.exs
Labels: status: in progress

#444 Create common_tests.run mix task
  .dialyzer.ignore-warnings
  apps/blockchain/lib/blockchain/chain.ex
  apps/blockchain/lib/blockchain/mix/tasks/common_tests.run.ex
  apps/blockchain/test/blockchain_test.exs
  apps/blockchain/test/support/blockchain_test_runner.ex
Labels: blockchain, status: in progress

#445 Update blockchain_test pattern matching
  apps/blockchain/test/blockchain_test.exs
Labels: blockchain, status: in progress

#443 Add a `sync_with_file` mix task
  .dialyzer.ignore-warnings
  apps/blockchain/lib/blockchain/chain.ex
  apps/blockchain/lib/blockchain/genesis.ex
  apps/blockchain/lib/mix/tasks/sync/from_file.ex
Labels: status: in progress

#447 Implement EIP-1234
  README.md
  apps/blockchain/lib/blockchain/block.ex
  apps/blockchain/lib/blockchain/chain.ex
  apps/blockchain/scripts/generate_blockchain_tests.ex
  apps/blockchain/test/blockchain/block_test.exs
  apps/blockchain/test/blockchain/chain_test.exs
  apps/blockchain/test/blockchain_test.exs
  apps/blockchain/test/support/constantinople_failing_tests.txt
  apps/evm/lib/block/header.ex
  apps/evm/test/block/header_test.exs
  chains/byzantium_test.json
  chains/constantinople_test.json
  chains/eip150_test.json
  chains/foundation.json
  chains/frontier_test.json
  chains/homestead_test.json
  chains/ropsten.json
Labels: blockchain, evm, status: in progress

#449 Add mix state_tests.run task
  .dialyzer.ignore-warnings
  apps/blockchain/lib/blockchain/chain.ex
  apps/blockchain/lib/mix/tasks/common_tests.run.ex
  apps/blockchain/lib/mix/tasks/state_tests.run.ex
  apps/blockchain/test/blockchain/state_test.exs
  apps/blockchain/test/support/state_test_runner.ex
Labels: status: in progress

#441 cache storage operations
  apps/blockchain/lib/blockchain/account.ex
  apps/blockchain/lib/blockchain/contract/create_contract.ex
  apps/blockchain/lib/blockchain/contract/message_call.ex
  apps/blockchain/lib/blockchain/interface/account_interface.ex
  apps/blockchain/lib/blockchain/interface/account_interface/cache.ex
  apps/blockchain/lib/blockchain/transaction.ex
  apps/blockchain/test/blockchain/contract/create_contract_test.exs
  apps/blockchain/test/blockchain/contract/message_call_test.exs
  apps/blockchain/test/blockchain/interface/account_interface/cache_test.exs
  apps/blockchain/test/blockchain/interface/account_interface_test.exs
Labels: status: in progress

#451 Turn EVM.Configuration into a behaviour
  .dialyzer.ignore-warnings
  apps/blockchain/lib/blockchain/chain.ex
  apps/blockchain/lib/blockchain/contract/create_contract.ex
  apps/blockchain/lib/blockchain/transaction.ex
  apps/blockchain/lib/blockchain/transaction/validity.ex
  apps/blockchain/scripts/generate_blockchain_tests.ex
  apps/blockchain/scripts/generate_state_tests.ex
  apps/blockchain/test/blockchain/state_test.exs
  apps/blockchain/test/support/state_test_runner.ex
  apps/evm/lib/evm/configuration.ex
  apps/evm/lib/evm/configuration/byzantium.ex
  apps/evm/lib/evm/configuration/constantinople.ex
  apps/evm/lib/evm/configuration/eip150.ex
  apps/evm/lib/evm/configuration/eip158.ex
  apps/evm/lib/evm/configuration/frontier.ex
  apps/evm/lib/evm/configuration/homestead.ex
  apps/evm/lib/evm/functions.ex
  apps/evm/lib/evm/gas.ex
  apps/evm/lib/evm/message_call.ex
  apps/evm/lib/evm/operation/system.ex
  apps/evm/lib/evm/refunds/sstore.ex
  apps/ex_wire/lib/ex_wire/config.ex
Labels: blockchain, evm, status: in progress

#448 Save state every 1000 blocks in SyncWithInfura
  apps/blockchain/scripts/sync_with_infura.ex
Labels: status: in progress
